name: genre-env
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pytorch
  - torchvision
  - torchaudio
  - torchtext
  - pip
  - pip:
      - nltk
      - spacy

