name: genre-env
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pip
  - pip:
      - nltk
      - spacy
      - --pre torch
      - --pre torchvision
      - --index-url https://download.pytorch.org/whl/nightly/cu130
