name: genre-env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pytorch
  - torchvision
  - torchaudio
  - torchtext
  - pip
  - pip:
      - nltk
      - spacy
      - sentence-transformers
