name: genre-env
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pip
  - pip:
      - tensorflow==2.15.0
      - nltk
      - spacy
      - tensorflow_hub==0.16.1
